# This file is part of curveball.
# https://github.com/yoavram/curveball

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Yoav Ram <yoav@yoavram.com>

# This file is modified from https://gist.github.com/dan-blanchard/7045057
language: python
python:
  - 2.7
notifications:
  email: true

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda pip

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION requests atlas numpy scipy matplotlib nose dateutil pandas statsmodels coverage lxml seaborn sympy xlrd pillow
  # Coverage packages are on my binstar channel
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install https://github.com/lmfit/lmfit-py/archive/800f3e40ef8ba977005d27a5d05fd231688a5749.zip
  - python setup.py install

# Configure a headless backend for matplotlib
before_script:
  - mkdir -p ~/.matplotlib/
# Ugly trick to avoid that the colon gets interpreted by the YAML parser.
  - |-
    echo "backend : Agg" > ~/.matplotlib/matplotlibrc

# Run test
script:  
  - nosetests --with-coverage --cover-package=curveball --cover-inclusive --cover-html --cover-html-dir=coverage_report