# This file is part of curveball.
# https://github.com/yoavram/curveball

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Yoav Ram <yoav@yoavram.com>

language: python

python:
    - "2.7"
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
