# This file is part of curveball.
# https://github.com/yoavram/curveball

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Yoav Ram <yoav@yoavram.com>

# This file is modified from https://gist.github.com/dan-blanchard/7045057
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"  
notifications:
  email: 
    - yoav@yoavram.com

# Setup anaconda
install:
  - sudo apt-get update
  - git fetch --unshallow
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi  
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --add channels conda-forge
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set anaconda_upload no
  - conda update -q conda pip
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n travis-env python=$TRAVIS_PYTHON_VERSION requests conda-build=1 conda=3 jinja2 anaconda-client atlas numpy scipy matplotlib pandas scikit-learn lxml seaborn sympy xlrd lmfit coverage nose pillow webcolors
  - conda activate travis-env
  - pip install codecov | cat
  - conda build -q conda-recipe
  - conda install --use-local -q curveball

# Run test
script:
  - curveball --version
  - nosetests tests --with-coverage --cover-package=curveball

after_success:
# Code coverage
  - codecov --token=$CODECOV_TOKEN
# Deploy to Anaconda.org (conditions inside script)
  - chmod +x ./deploy_anaconda.sh

before_deploy:
# Build docs
  - pip install --upgrade sphinx sphinx-rtd-theme numpydoc | cat
  - cd docs
  - make html
  - cd ..
# Install netlify
  - npm install -g netlify-cli

deploy:
# Deploy to netlify.com
  - provider: script
    script: netlify deploy -p docs/_build/html --access-token $NETLIFY_TOKEN
    on:
      repo: yoavram/curveball
      branch: master
    skip_cleanup: true
# Deploy to Anaconda.org
  - provider: script
    script: ./deploy_anaconda.sh
    on:
      tags: true
      repo: yoavram/curveball
    skip_cleanup: true
