# This file is part of curveball.
# https://github.com/yoavram/curveball

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Yoav Ram <yoav@yoavram.com>

# This file is modified from https://gist.github.com/dan-blanchard/7045057
language: python
python:
  - 2.7
  - 3.4
  - 3.5
notifications:
  email: 
    - yoav@yoavram.com

# Setup anaconda
before_install:
  - git fetch --unshallow
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - export MPLBACKEND=agg
  - conda update --yes -q conda pip
  - conda config --add channels yoavram
  - conda config --add channels conda-forge
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - pip install codecov | cat

# Install packages
install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION requests conda-build=1 jinja2 anaconda-client atlas numpy scipy matplotlib python-dateutil pandas scikit-learn lxml seaborn sympy xlrd lmfit coverage nose pillow
  - conda build -q conda-recipe
  - conda install --use-local -q curveball

# Run test
script:
  - curveball --version
  - nosetests tests --with-coverage --cover-package=curveball

after_success:
# Code coverage
  - codecov --token=$CODECOV_TOKEN
# Deploy to Anaconda.org (conditions inside script)
  - chmod +x ./deploy_anaconda.sh

before_deploy:
# Build docs
  - pip install --upgrade sphinx sphinx-rtd-theme numpydoc | cat
  - cd docs
  - make html
  - cd ..
# Install netlify
  - npm install -g netlify-cli

deploy:
# Deploy to netlify.com
  - provider: script
    script: netlify deploy -p docs/_build/html --access-token $NETLIFY_TOKEN
    on:
      repo: yoavram/curveball
      branch: master
    skip_cleanup: true
# Deploy to Anaconda.org
  - provider: script
    script: ./deploy_anaconda.sh
    on:
      tags: true
      repo: yoavram/curveball
    skip_cleanup: true
