name: D:\Anaconda3\envs\curveball
dependencies:
- backports.shutil_get_terminal_size=1.0.0
- backports_abc=0.4
- ca-certificates=2016.2.28
- click=6.6
- cycler=0.10.0
- decorator=4.0.9
- emcee=2.1.0
- fastcache=1.0.2
- freetype=2.6.3
- future=0.15.2
- ipykernel=4.3.1
- ipython=4.2.0
- ipython_genutils=0.1.0
- jpeg=8d
- jupyter_client=4.2.2
- jupyter_core=4.1.0
- libpng=1.6.21
- libtiff=4.0.6
- lmfit=0.9.3
- lxml=3.6.0
- matplotlib=1.5.1
- mkl=11.3.3
- mpmath=0.19
- numpy=1.11.0
- openssl=1.0.2h
- pandas=0.18.1
- pickleshare=0.7.2
- pip=8.1.1
- pyparsing=2.1.4
- pyqt=4.11.4
- python=3.4.4
- python-dateutil=2.5.3
- pytz=2016.4
- pyzmq=15.2.0
- qt=4.8.7
- scikit-learn=0.17.1
- scipy=0.17.1
- seaborn=0.7.0
- setuptools=21.2.1
- simplegeneric=0.8.1
- sip=4.16.9
- six=1.10.0
- sympy=1.0
- tk=8.5.19
- tornado=4.3
- traitlets=4.2.1
- wheel=0.29.0
- xlrd=0.9.4
- zlib=1.2.8
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
