name: D:\Anaconda3\envs\curveball
dependencies:
- ca-certificates=2016.2.28
- cycler=0.10.0
- emcee=2.1.0
- fastcache=1.0.2
- freetype=2.6.3
- jpeg=8d
- libpng=1.6.22
- libtiff=4.0.6
- lmfit=0.9.3
- lxml=3.6.0
- matplotlib=1.5.1
- mkl=11.3.3
- mpmath=0.19
- numpy=1.11.0
- openssl=1.0.2h
- pandas=0.18.1
- pip=8.1.2
- pyparsing=2.1.4
- pyqt=4.11.4
- python=3.5.1
- python-dateutil=2.5.3
- pytz=2016.4
- qt=4.8.7
- scikit-learn=0.17.1
- scipy=0.17.1
- seaborn=0.7.0
- setuptools=23.0.0
- sip=4.18
- six=1.10.0
- sympy=1.0
- vs2015_runtime=14.00.23026.0
- wheel=0.29.0
- xlrd=1.0.0
- zlib=1.2.8
- pip:
  - alabaster==0.7.8
  - babel==2.3.4
  - click==6.6
  - colorama==0.3.7
  - coverage==4.1
  - docutils==0.12
  - future==0.15.2
  - imagesize==0.7.1
  - jinja2==2.8
  - markupsafe==0.23
  - nose==1.3.7
  - numpydoc==0.6.0
  - pillow==3.2.0
  - pygments==2.1.3
  - snowballstemmer==1.2.1
  - sphinx==1.4.4
  - sphinx-rtd-theme==0.1.9

