name: D:\workspace\curveball_project\code\venv3
dependencies:
- coverage=4.0=py34_0
- dateutil=2.4.1=py34_0
- fastcache=1.0.2=py34_0
- lxml=3.4.4=py34_0
- matplotlib=1.4.3=np19py34_1
- nose=1.3.7=py34_0
- numpy=1.9.3=py34_0
- pandas=0.16.2=np19py34_0
- patsy=0.4.0=np19py34_0
- pillow=3.0.0=py34_0
- pip=7.1.2=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.10.4=py34_1
- python=3.4.3=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.6=py34_0
- requests=2.8.0=py34_0
- scipy=0.16.0=np19py34_0
- seaborn=0.6.0=np19py34_0
- setuptools=18.3.2=py34_0
- six=1.10.0=py34_0
- statsmodels=0.6.1=np19py34_0
- sympy=0.7.6.1=py34_0
- wheel=0.26.0=py34_1
- xlrd=0.9.4=py34_0
- pip:
  - alabaster==0.7.6
  - babel==2.1.1
  - click==5.1
  - colorama==0.3.3
  - curveball (d:\workspace\curveball_project\code)==0.1.8
  - docutils==0.12
  - future==0.15.2
  - jinja2==2.8
  - lmfit==0.9.0
  - markupsafe==0.23
  - pygments==2.0.2
  - snowballstemmer==1.2.0
  - sphinx==1.3.1
  - sphinx-rtd-theme==0.1.9
  - versioneer==0.15

